src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_complet = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // $this->plainPassword = null;
    }

    public function getNomComplet(): ?string
    {
        return $this->nom_complet;
    }

    public function setNomComplet(?string $nom_complet): static
    {
        $this->nom_complet = $nom_complet;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route; // pour Symfony 6.4+
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('app_home'); // ou une autre page "cible"
        // }

        // erreur de connexion s'il y en a une
        $error = $authenticationUtils->getLastAuthenticationError();
        // saisi par l'utilisateur
        $lastUsername = $authenticationUtils->getLastUsername();

        // renvoi le template du formulaire de connexion
        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        // peut être vide & sera interceptée par la config
        // pare-feu (firewall) ds security.yaml
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Connexion Espace Agence{% endblock %}

{% block body %}

<div class="row justify-content-center">
    <div class="col-md-6 col-lg-5 col-xl-4">
        <div class="content-card mt-5"> 
            <form method="post">
                <h1 class="h3 mb-4 fw-normal text-center">Connexion Espace Agence</h1>

                {% if error %}
                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                {% endif %}

                {% if app.user %}
                    <div class="alert alert-info mb-3">
                        Vous êtes connecté en tant que {{ app.user.userIdentifier }}.<br>
                        <a href="{{ path('app_home') }}" class="alert-link">Accueil collaborateur Agence</a> ou 
                        <a href="{{ path('app_logout') }}" class="alert-link">vous déconnecter</a>.
                    </div>
                {% else %}
                    <div class="form-floating mb-3">
                        <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" placeholder="vous@exemple.com" autocomplete="email" required autofocus>
                        <label for="inputEmail">Adresse e-mail</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Mot de passe" autocomplete="off" required>
                        <label for="inputPassword">Mot de passe</label>
                    </div>

                    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">

                    <div class="checkbox mb-3">
                        <label>
                            <input type="checkbox" name="_remember_me"> Se souvenir de moi
                        </label>
                    </div>

                    <button class="w-100 btn btn-lg btn-primary" type="submit" style="background-color: var(--bleu-majorelle); border-color: var(--bleu-majorelle);">
                        Se connecter
                    </button>

                    <div class="mt-3 text-center">
                        <a href="{{ path('app_public_home') }}">Retour à l'accueil public</a>
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}